language: node_js

node_js:
  - 0.12

before_install:
  - npm install -g gulp
  - npm install -g bower

addons:
  code_climate:
    repo_token:
      secure: "eFmBuD3tq5qhjoA8ksu+gxBi5bwdw01bTHHQWOST6+gkAHgM6X7vnl7leU1ZgsXB9BRtVNwK9DaTc/OQA55Jzm1NMUtnhN2NWlZ3/fdWpCR3YaJ2KlLUNBQ05OSPcn6ahXpngpaRLWThwY0DysEhYUOSGE6IiZ3SMQz6P1l2Fy+NNq+uZeYZ512guPePmON5eMPvfRANm0Oz96LCo7TNc5kPZ5YRzmdBbr7M1ffeOpSDV3SWB63i4sWj7Wof/8tRzPyJZ3ercfewvz6Uuoay0TM/yR0OGLM0sWwJpEyb/B4hS/OHoYwySd9vvmTQiW/n1Na1VxWisKo7IuDwxhGoI83e0O4NeiXaYSGD/41vZqajVMzCzi9UzHn6fIG9jSz45HJYqNhybtoyMVufH+wXoH1A/R9pCXhgGMv2fDROJMTjlqOn66JkoWpps4g0tPN5aOavNBxHlkgXjeeZyKS6cjc0dVWX+Z/oRvD7sDH6EyVZ0NkC1wevJvGdX+2t0pfAjLKib/GEbrWEYgV0KujbYnjhJ/W+l2g9kkBL+9XG8NuzWqqzqsEDpL+kFOJmVZqtOHvBea8iMpQJ1ne+M3pGlNGlBApbGQrKpF6xvxwd8o/JhxlQrM5ic6nZyejpLqrsXkjYV7Sfb8LcmGcRZTIzCiFQ81aHLf2L6Hfx6dUYIsU="
script:
  - bower install
  - gulp ci

after_script:
  - codeclimate < coverage/lcov.info
